#include <stdio.h>
#include "GlobalDll.h"
#include "../core/InstrumentLogger.h"

using namespace std; bool Global :: NaNcheck;
bool Global :: LOGVARLOAD;
long Global :: GroupCntTrk;
long Global :: StructCntTrk;
long Global :: Freq;
long Global :: DTindx;
long Global :: DTmin;
long Global :: DTmax;
long Global :: IndxMin;
long Global :: IndxMax;
long Global :: maxobs;
long Global :: maxlay;
long Global :: maxhru;
long Global :: nobs;
long Global :: nlay;
long Global :: nhru;
long Global :: CRHMStatus;
std :: string Global :: CurrentModuleRun;
long Global :: CRHMControlSaveCnt;
BitSet Global :: RunUpBitSet;
std :: set < std :: string > * Global :: ModuleBitSet;
double Global :: Interval;
double Global :: DTstart;
double Global :: DTend;
TDateTime Global :: DTnow;
TDateTime Global :: RapidAdvanceTo;
TDateTime Global :: LoopTo;
long Global :: LoopCnt;
long Global :: LoopCntDown;
TBuild Global :: BuildFlag;
TIMEFORMAT Global :: TimeFormat;
MapVar Global :: MapVars;
MapVar Global :: MapVarsGet;
MapVar Global :: MapVarsPut;
MapVar Global :: MapObsGet;
MapPar Global :: MapPars;
MapPar Global :: SharedMapPars;
Mapstr Global :: Mapgetvar;
Mapstr Global :: Mapputvar;
Mapstr Global :: Mapreadvar;
Mapstr Global :: Mapdeclvar;
Mapstr Global :: Mapdeclpar;
Mapstr Global :: Mapdeclobs;
Mapstr Global :: Mapdeclstat;
Mapstr2 Global :: MapAKA;
std :: map < std :: string, ClassModule * > * (Global :: AllModulesList);
std :: list < std :: pair < std :: string, ClassModule * >> * (Global :: OurModulesList);
std :: list < std :: pair < std :: string, unsigned short >> * (Global :: OurModulesVariation);
std :: vector < std :: string > * (Global :: MacroModulesList);
std :: list < std :: pair < std :: string, int >> * (Global :: AllModelsList);
std :: list < std :: pair < std :: string, Administer * >> * (Global :: ModelModulesList);
std :: map < std :: string, int > * (Global :: OurHelpList);
std :: list < std :: pair < std :: string, ClassModule * >> * (Global :: PendingDLLModuleList);
std :: list < std :: string > * (Global :: ReportList);
std :: list < std :: string > * (Global :: DeclRootList);
std :: vector < std :: string > * (Global :: OldModuleName);
std :: vector < std :: string > * (Global :: NewModuleName);
double * Global :: lapse_rate;
double * Global :: ppt_adj;
double * Global :: hru_elev;
long ** Global :: HRU_OBS;
double * Global :: Warming_t;
double * Global :: Warming_p;
long * Global :: RH_VP_flag;
long * Global :: RH_VP_flag2;
long Global :: RH_EA_obs;
long Global :: OBS_AS_IS;
long Global :: WQ_prj;
double ** Global :: OBS_ELEV;
long ** Global :: HRU_OBS_DIRECT;
double ** Global :: obs_t;
double ** Global :: obs_ea;
double ** Global :: obs_rh;
double ** Global :: obs_t_obs;
ClassVar * Global :: thisVar;
